apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: bpf-process-monitor
  name: bpf-process-monitor
spec:
  template:
    metadata:
      labels:
        k8s-app: bpf-process-monitor
    spec:
      containers:
      - image: docker.io/danwent/bpf-process-monitor:v34
        imagePullPolicy: IfNotPresent
        name: cilium-process-monitor
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - CAP_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sys/fs/bpf
          name: bpf-maps
        - mountPath: /sys/kernel/debug
          name: bpf-debug
        - mountPath: /var/run/cilium
          name: cilium-run
        - mountPath: /var/run/docker.sock
          name: docker-socket
          readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: cilium
      serviceAccountName: cilium
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node.kubernetes.io/not-ready
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - effect: NoSchedule
        key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - hostPath:
          path: /var/run/cilium
          type: DirectoryOrCreate
        name: cilium-run
      - hostPath:
          path: /sys/fs/bpf
          type: DirectoryOrCreate
        name: bpf-maps
      - hostPath:
          path: /sys/kernel/debug
          type: DirectoryOrCreate
        name: bpf-debug
      - hostPath:
          path: /var/run/docker.sock
          type: Socket
        name: docker-socket
  templateGeneration: 10
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 2
    type: RollingUpdate
